# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a022b17f7165570fac1ae13b59ac4c153fa7b87c3694e0d59ac54f08dc8171766951021d42958c3a09adffdcfa772d87b99ebabd04053ee67ea7cc1fea275d99

test:
  secret_key_base: e34ffd9c2873ad31bf710d65445b49c3fd2c110868a774a113d1b49c9f8c1ab4c6061df55f3c8dfffd137eaafe6740fe24c0ea352608765308df3fe604a51435

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
